### ISSUE TITLE
Handling too many requests and other server side errors

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/gemmapy#24]
gemma.R's body handles errors by waiting for a few seconds before repeating a request. This would have to be done by an edit to the api template itself

**Comment by arteymix** [comment]
We can also increase the req/seq on the backend. There's a limit of 10 right now with 100 concurrent requests.

**Comment by oganm** [comment]
the message we get is [this](https://github.com/PavlidisLab/gemmapy/actions/runs/9025020613/job/24800095346#step:5:183) one, but requests should not be concurrent as far as i know

**Comment by oganm** [comment]
- Tests now include a 1 second pause between each of them
- sdk template now automatically retries any attempt that returns a 429 or 500 error after 3 seconds up to 3 times. This behaviour is identical to gemma.R which has been reliable enough

**Comment by arteymix** [comment]
urllib3 has a built-in mechanism for retrying requests and also handling redirections.

https://urllib3.readthedocs.io/en/stable/user-guide.html#retrying-requests

You can pass a [Retry](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.Retry) object that can be configured with your retry policy and also honor the `Retry-After` header. The API can respond with a `429` when the inference times out.

**Comment by arteymix** [comment]
I think this has to be done in https://github.com/PavlidisLab/gemmapy/blob/master/gemmapy/sdk/rest.py.
